application: k2icecapade
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats : on
- deferred : on

handlers:
- url: /joyride/.*
  script: joyride.app

- url: /
  static_dir: _site

skip_files: |
   ^(.*/)?(
   (app\.yaml)|
   (app\.yml)|
   (index\.yaml)|
   (index\.yml)|
   (#.*#)|
   (.*~)|
   (.*\.py[co])|
   (.*/RCS/.*)|
   (\..*)|
   (_inclues\/.*)|
   (_layouts\/.*)|
   (_plugins\/.*)|
   (_posts\/.*)|
   (assets\/.*)|
   (static\/.*)|
   )$
