application: k2icecapade
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats : on
- deferred : on

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /static/
  static_dir: static

- url: /joyride/.*
  script: joyride.app

- url: /.*
  script: main.app