application: k2icecapade
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats : on
- deferred : on

handlers:
- url: /timeframe/.*
  script: timeframe.app

- url: /assets
  static_dir: _site/assets

- url: /apps
  static_dir: _site/apps

- url: /(.*)/(.*)
  static_files: _site/\1/\2/index.html
  upload: _site/(.*)/(.*)/index.html

- url: /
  static_files: _site/index.html
  upload: _site/index.html

- url: /(.*)
  static_files: _site/\1
  upload: _site/.*

skip_files: |
   ^(.*/)?(
   (app\.yaml)|
   (app\.yml)|
   (index\.yaml)|
   (index\.yml)|
   (#.*#)|
   (.*~)|
   (.*\.py[co])|
   (.*/RCS/.*)|
   (\..*)|
   (_inclues\/.*)|
   (_layouts\/.*)|
   (_plugins\/.*)|
   (_posts\/.*)|
   (static\/.*)|
   )$
